### ISSUE TITLE
Task

### ISSUE THREAD

**Issue by OfficialByronCloete** [OfficialByronCloete/ADPAssignmentTracker#71]

**Comment by CalebYPI** [comment]
Hey Byron, my phone isn't working at the moment and I apologize for not completing the deliverable, I'll get that done ASAP. I was going through the project and noticed that most of the repository classes were commented out. I wanted to find out the reason why.

**Comment by OfficialByronCloete** [comment]
They were commented out because we're not testing the repository classes for these deliverables only the Controller classes.
